# Generated by Django 6.0.3 on 2026-04-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_unit'),
        ('user', '0003_rename_lastname_client_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('mains', 'Mains')], default='normal', max_length=20)),
                ('states', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invoiced', 'Invoiced')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_order_items', to='user.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_order_items', to='catalog.contract')),
                ('parent_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Orders_Manage.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('mains', 'Mains')], default='normal', max_length=20)),
                ('qte', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(choices=[('L', 'Liter'), ('HL', 'Hectoliter'), ('KG', 'Kilogram'), ('TM', 'Ton')], max_length=20)),
                ('states', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invoiced', 'Invoiced')], default='pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_orderProduct_items', to='Orders_Manage.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_orderProduct_items', to='catalog.product')),
            ],
        ),
    ]
