# Generated by Django 5.2.7 on 2026-04-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0001_initial'),
        ('order_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='validated_by',
            new_name='stated_by',
        ),
        migrations.AddField(
            model_name='order',
            name='client_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fufilled_orders', to='order_client.orderclient'),
            preserve_default=False,
        ),
    ]
