# Generated by Django 5.2.7 on 2026-04-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0001_initial'),
        ('Orders_Manage', '0002_rename_validated_by_order_stated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_order_items', to='Invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced')], default='pending', max_length=20),
        ),
    ]
