# Generated by Django 6.0.3 on 2026-04-10 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0002_invoice_validated_by_alter_invoice_type'),
        ('Orders_Manage', '0003_alter_order_invoice_alter_order_state'),
        ('catalog', '0003_remove_product_qte_left_remove_producttype_unit_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='states',
            field=models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invoiced', 'Invoiced')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='unit',
            field=models.CharField(choices=[('L', 'Liter'), ('HL', 'Hectoliter'), ('KG', 'Kilogram'), ('TM', 'Ton')], default='kg', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_order_items', to='user.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_order_items', to='catalog.contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_order_items', to='Invoices.invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('minus', 'Minus')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_orderProduct_items', to='Orders_Manage.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_orderProduct_items', to='catalog.product'),
        ),
    ]
