# Generated by Django 6.0.3 on 2026-04-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0004_remove_order_state_order_states_orderproduct_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stated_by',
            new_name='validated_by',
        ),
    ]
