# Generated by Django 6.0.3 on 2026-04-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0005_rename_stated_by_order_validated_by'),
        ('order_client', '0002_orderproductclient_qte_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientOrder_order_items', to='order_client.orderclient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('minus', 'Minus')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='unit',
            field=models.CharField(choices=[('L', 'L'), ('HL', 'HL'), ('KG', 'KG'), ('TM', 'TM')], max_length=20),
        ),
    ]
