# Generated by Django 6.0.3 on 2026-04-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0006_alter_order_client_order_alter_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='states',
            field=models.CharField(default='ee', max_length=20),
            preserve_default=False,
        ),
    ]
