# Generated by Django 6.0.3 on 2026-04-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0007_orderproduct_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='states',
        ),
    ]
