# Generated by Django 6.0.3 on 2026-04-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0008_remove_orderproduct_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='states',
            field=models.CharField(choices=[('loading', 'Loading'), ('valid', 'Valid'), ('invoiced', 'Invoiced')], default='loading', max_length=20),
        ),
    ]
