# Generated by Django 6.0.3 on 2026-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_Manage', '0009_alter_order_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='states',
            field=models.CharField(choices=[('loading', 'Loading'), ('validated', 'Validated'), ('invoiced', 'Invoiced')], default='loading', max_length=20),
        ),
    ]
