# Generated by Django 5.2.7 on 2026-04-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilo Gram')], db_index=True, default='litre', max_length=20),
        ),
    ]
