# Generated by Django 5.2.7 on 2026-04-10 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='qte_global',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='qte_used',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
    ]
