# Generated by Django 5.2.7 on 2026-04-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilo Gram')], db_index=True, max_length=20),
        ),
    ]
