# Generated by Django 5.2.7 on 2026-04-10 20:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_contract_qte_global_alter_contract_qte_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qte_left',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('litre', 'Litre'), ('kg', 'Kilo Gram')], db_index=True, default='kg', max_length=20),
        ),
    ]
