# Generated by Django 6.0.3 on 2026-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_qte_left_remove_producttype_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'L'), ('HL', 'HL'), ('KG', 'KG'), ('TM', 'TM')], db_index=True, default='L', max_length=20),
        ),
    ]
