# Generated by Django 6.0.3 on 2026-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='unit',
            field=models.CharField(choices=[('L', 'L'), ('HL', 'HL'), ('KG', 'KG'), ('TM', 'TM')], default='L', max_length=20),
            preserve_default=False,
        ),
    ]
