# Generated by Django 5.2.7 on 2026-04-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderclient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordersclient', to='user.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordersclient', to='catalog.contract')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductclient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.DecimalField(decimal_places=3, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productsclient', to='order_client.orderclient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productsclient', to='catalog.product')),
            ],
        ),
    ]
