# Generated by Django 6.0.3 on 2026-04-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_remove_invoice_date_creat_invoice_ht_invoice_ttc_and_more'),
        ('Orders_Manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='states',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_order_items', to='Invoices.invoice'),
            preserve_default=False,
        ),
    ]
