# Generated by Django 5.2.7 on 2026-04-10 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductclient',
            name='qte_taken',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
    ]
