# Generated by Django 5.2.7 on 2026-04-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_unit'),
        ('order_client', '0002_orderproductclient_qte_taken'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclient',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_Ordersclient_items', to='user.client'),
        ),
        migrations.AlterField(
            model_name='orderclient',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_Orderclient_items', to='catalog.contract'),
        ),
        migrations.AlterField(
            model_name='orderproductclient',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderclient_Orderproductclient_items', to='order_client.orderclient'),
        ),
        migrations.AlterField(
            model_name='orderproductclient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_OrderProductclient_items', to='catalog.product'),
        ),
    ]
