# Generated by Django 6.0.3 on 2026-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0003_alter_orderclient_client_alter_orderclient_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductclient',
            name='unit',
            field=models.CharField(choices=[('L', 'L'), ('HL', 'HL'), ('KG', 'KG'), ('TM', 'TM')], default='L', max_length=20),
            preserve_default=False,
        ),
    ]
