# Generated by Django 6.0.3 on 2026-04-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0003_orderclient_pickup_date_alter_orderclient_client_and_more'),
        ('order_client', '0004_orderproductclient_unit'),
    ]

    operations = [
    ]
