# Generated by Django 6.0.3 on 2026-04-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0005_merge_20260415_1749'),
        ('order_client', '0005_merge_20260415_1854'),
    ]

    operations = [
    ]
