# Generated by Django 6.0.3 on 2026-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0006_merge_20260417_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclient',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('loadin', 'Loadin'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
