# Generated by Django 6.0.3 on 2026-04-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0007_alter_orderclient_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclient',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('loading', 'Loading'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
