# Generated by Django 6.0.3 on 2026-04-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0008_alter_orderclient_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductclient',
            name='unit',
        ),
    ]
