# Generated by Django 5.2.7 on 2026-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0009_remove_orderproductclient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductclient',
            name='unit',
            field=models.CharField(choices=[('L', 'L'), ('HL', 'HL'), ('KG', 'KG'), ('TM', 'TM')], db_index=True, default='L', max_length=20),
        ),
    ]
