# Generated by Django 5.2.7 on 2026-04-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_client', '0010_orderproductclient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclient',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('loading', 'Loading'), ('validated', 'Validated'), ('invoiced', 'Invoiced'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
