# Generated by Django 5.2.7 on 2026-04-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
