# Generated by Django 6.0.3 on 2026-04-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_balance_id'),
        ('user', '0003_rename_lastname_client_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_balances', to='user.client'),
        ),
    ]
