# Generated by Django 6.0.3 on 2026-04-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('TVA_prix', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_creat', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('mains', 'Mains')], max_length=20)),
                ('states', models.CharField(choices=[('valid', 'Valid'), ('no_valid', 'No_Valid')], default='no_valid', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_invoice_items', to='catalog.contract')),
            ],
        ),
    ]
