# Generated by Django 5.2.7 on 2026-04-09 19:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_de_facteration', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('minus', 'Minus')], default='normal', max_length=20)),
                ('states', models.CharField(choices=[('valid', 'Valid'), ('no_valid', 'No_Valid')], default='no_valid', max_length=20)),
                ('HT', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('TVA', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('TTC', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_invoice_items', to='catalog.contract')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineAllInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('tax_name', models.CharField(max_length=50)),
                ('qte', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unit', models.CharField(choices=[('L', 'Liter'), ('HL', 'Hectoliter'), ('KG', 'Kilogram'), ('TM', 'Ton')], max_length=20)),
                ('tax_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_InvoiceLineAllInfo_items', to='Invoices.invoice')),
            ],
        ),
    ]
