# Generated by Django 6.0.3 on 2026-04-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Invoices', '0001_initial'),
        ('Orders_Manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product_items', to='Orders_Manage.orderproduct'),
        ),
    ]
