# Generated by Django 6.0.3 on 2026-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_invoiceline_delete_invoicelineallinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('minus', 'Minus')], default='normal', max_length=20),
        ),
    ]
