# Generated by Django 6.0.3 on 2026-04-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_creat',
        ),
        migrations.AddField(
            model_name='invoice',
            name='HT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='TTC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='TVA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_de_facteration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('plus', 'Plus'), ('mains', 'Mains')], default='normal', max_length=20),
        ),
        migrations.DeleteModel(
            name='InvoiceLine',
        ),
    ]
