# Generated by Django 6.0.3 on 2026-04-09 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_remove_invoice_date_creat_invoice_ht_invoice_ttc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineAllInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('tax_name', models.CharField(max_length=50)),
                ('qte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('L', 'Liter'), ('HL', 'Hectoliter'), ('KG', 'Kilogram'), ('TM', 'Ton')], max_length=20)),
                ('tax_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_InvoiceLineAllInfo_items', to='Invoices.invoice')),
            ],
        ),
    ]
