# Generated by Django 6.0.3 on 2026-04-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_alter_invoice_type'),
        ('catalog', '0005_contract_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='product_name',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='product_InvoiceLine_items', to='catalog.product'),
            preserve_default=False,
        ),
    ]
