# Generated by Django 6.0.3 on 2026-04-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0005_remove_invoiceline_product_name_invoiceline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='states',
            field=models.CharField(choices=[('validated', 'Validated'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
