# Generated by Django 6.0.3 on 2026-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0006_alter_invoice_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='Tva',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
            preserve_default=False,
        ),
    ]
