# Generated by Django 5.2.7 on 2026-04-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('lastName', models.CharField(max_length=254)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('superAdmin', 'Super Admin')], default='client', max_length=15)),
                ('email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('link', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.client')),
            ],
        ),
    ]
