# Generated by Django 5.2.7 on 2026-04-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaxProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('Hl', 'Hl'), ('Tm', 'Tm'), ('l', 'L'), ('%', 'Pr')], max_length=20)),
                ('par_unit', models.DecimalField(decimal_places=3, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_taxProduct_items', to='catalog.product')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_taxProduct_items', to='Tax_Service.tax')),
            ],
        ),
    ]
