# Generated by Django 6.0.3 on 2026-04-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax_Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxproduct',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('HL', 'Hectoliter'), ('TM', 'Ton'), ('L', 'Liter'), ('PR', 'Percentage')], max_length=20),
        ),
    ]
