# Generated by Django 6.0.3 on 2026-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax_Service', '0002_alter_taxproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxproduct',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('HL', 'HL'), ('TM', 'TM'), ('L', 'L'), ('PR', 'PR')], max_length=20),
        ),
    ]
