# Generated by Django 6.0.3 on 2026-04-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax_Service', '0003_alter_taxproduct_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
