# Generated by Django 6.0.3 on 2026-04-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tax_Service', '0004_tax_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='description',
        ),
    ]
