# Generated by Django 6.0.3 on 2026-04-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tax_Service', '0005_remove_tax_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
